services:
  # Go приложение
  app:
    build: .
    container_name: go-app
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: tmeeting
      DB_USER: postgres
      DB_PASSWORD: coolpassword
      HTTP_PORT: "33"
    ports:
      - "33:33"
    depends_on:
      - db
    volumes:
      - ./config.yml:/app/config.yml:ro

  # PostgreSQL
  db:
    image: postgres:18-alpine
    environment:
      HTTP_PORT: "33"
      POSTGRES_DB: tmeeting
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: coolpassword
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  db_data:
